// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using UltraMusic.Models;

namespace UltraMusic
{
	public partial class SideBarController : NSViewController
	{
		public SideBarController (IntPtr handle) : base (handle)
		{
          
		}

        private MusicProvider currentProvider = MusicProvider.None;

        private void HandleClick(MusicProvider provider) {
            if (provider == currentProvider) return;

            currentProvider = provider;
            RaiseProviderClicked(provider);
        }

        public override void AwakeFromNib()
        {
            base.AwakeFromNib();

            SideBarSourceList.Initialize();

            var providers = new SideBarItem("Music Provider");

            providers.AddItem("Saavn", () => { HandleClick(MusicProvider.Saavn); });
            providers.AddItem("Amazon Prime", () => { HandleClick(MusicProvider.AmazonPrime); });
            providers.AddItem("Google Music", () => { HandleClick(MusicProvider.GoogleMusic); });

            SideBarSourceList.AddItem(providers);
            SideBarSourceList.ReloadData();
            SideBarSourceList.ExpandItem(null, true);
        }

        public delegate void ProviderClickedDelegate(MusicProvider provider);
        public event ProviderClickedDelegate ProviderClicked;

        internal void RaiseProviderClicked(MusicProvider provider)
        {
            ProviderClicked?.Invoke(provider);
        }

    }
}
