// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using UltraMusic.Helpers;

namespace UltraMusic.Views
{
	public partial class MainWindowController : NSWindowController
	{
		public MainWindowController (IntPtr handle) : base (handle)
		{
		}

        public override void WindowDidLoad()
        {
            base.WindowDidLoad();

            ViewModelLocator.MainViewModel.PropertyChanged += MainViewModel_PropertyChanged;
        }

        partial void PlayPauseButtonClicked(NSObject sender)
        {
            //(ContentViewController as MasterDetailController).PlayPauseClicked();
            ViewModelLocator.MainViewModel.Pause();
        }

        void MainViewModel_PropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            switch (e.PropertyName)
            {
                case nameof(ViewModels.MainViewModel.PlayerState):
                    PlayerStateChanged();
                    break;
            }
        }

        private void PlayerStateChanged()
        {
            switch (ViewModelLocator.MainViewModel.PlayerState)
            {
                case Portable.ViewModels.PlayerState.Idle:
                    PlayPauseButton.Enabled = false;
                    break;
                default:
                    PlayPauseButton.Enabled = true;
                    break;
            }
        }
    }
}
