// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using AppKit;
using CoreGraphics;
using Foundation;
using UltraMusic.Helpers;
using UltraMusic.Portable.Models;
using UltraMusic.Portable.ViewModels;
using WebKit;

namespace UltraMusic.Views
{
    public partial class MasterDetailController :
    NSSplitViewController
    {
        private SideBarController leftController;
        private WebRendererController rightController;
        private MainViewModel viewModel;

        public MasterDetailController(IntPtr handle) : base(handle)
        {
            Initialize();
        }

        private void Initialize()
        {
            viewModel = ViewModelLocator.MainViewModel;
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var children = ChildViewControllers;
            leftController = SideBarItem.ViewController as SideBarController;
            rightController = WebRendererItem.ViewController as WebRendererController;

            leftController.ProviderClicked += RenderProvider;
            viewModel.PropertyChanged += ViewModel_PropertyChanged;
            viewModel.Loaded();
        }

        void ViewModel_PropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            string propertyName = e.PropertyName;
            switch (propertyName)
            {
                case nameof(viewModel.MusicProviders):
                    ProvidersChanged();
                    break;
            }
        }

        private void ProvidersChanged() 
        {
            leftController.RenderProviders(viewModel.MusicProviders);
        }


        private void RenderProvider(MusicProvider provider)
        {
            var rightView = rightController.View;

            if (rightView.Subviews.Length > 0)
            {
                rightView.Subviews[0].RemoveFromSuperview();
            }
            var webView = GetView(provider, rightController.View.Frame);
            rightView.AddSubview(webView);

            webView.TopAnchor.ConstraintEqualToAnchor(rightView.TopAnchor).Active = true;
            webView.BottomAnchor.ConstraintEqualToAnchor(rightView.BottomAnchor).Active = true;
            webView.LeftAnchor.ConstraintEqualToAnchor(rightView.LeftAnchor).Active = true;
            webView.RightAnchor.ConstraintEqualToAnchor(rightView.RightAnchor).Active = true;
        }

        private Dictionary<string, WKWebView> webViews;

        private WKWebView GetView(MusicProvider provider, CGRect rect)
        {
            if (webViews == null)
                webViews = new Dictionary<string, WKWebView>();
            if (!webViews.ContainsKey(provider.Id))
            {
                var webView = new WKWebView(rect, new WKWebViewConfiguration())
                {
                    CustomUserAgent = "Mozilla/5.0 " +
                    "(Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 " +
                    "(KHTML, like Gecko) Version/12.0 Safari/605.1.15",
                    AutoresizingMask = NSViewResizingMask.HeightSizable | NSViewResizingMask.WidthSizable
                };
                webView.TranslatesAutoresizingMaskIntoConstraints = false;

                var req = new NSUrlRequest(new NSUrl(provider.Url));

                webView.LoadRequest(req);
                webViews[provider.Id] = webView;
            }
            return webViews[provider.Id];
        }
    }
}
