// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using AppKit;
using UltraMusic.Models;
using UltraMusic.Portable.Models;

namespace UltraMusic.Views
{
    public partial class SideBarController : NSViewController
	{
        private List<MusicProvider> providers;

		public SideBarController (IntPtr handle) : base (handle)
		{
          
		}

        private MusicProvider currentProvider = null;

        private void HandleClick(MusicProvider provider) {
            if (provider == currentProvider) return;

            currentProvider = provider;
            RaiseProviderClicked(provider);
        }


        public void RenderProviders(List<MusicProvider> providers) 
        {
            this.providers = providers;
            RenderProviders();
        }

        private void RenderProviders()
        {
            if (providers == null || providers.Count == 0)
                return;

            SideBarSourceList.Initialize();

            var group = new SideBarItem("Music Providers");

            foreach (var provider in providers)
            {
                group.AddItem(provider.Name, () => { HandleClick(provider); });
            }

            SideBarSourceList.AddItem(group);
            SideBarSourceList.ReloadData();
            SideBarSourceList.ExpandItem(null, true);
        }

        public override void AwakeFromNib()
        {
            base.AwakeFromNib();

            RenderProviders();
        }

        public delegate void ProviderClickedDelegate(MusicProvider provider);
        public event ProviderClickedDelegate ProviderClicked;

        internal void RaiseProviderClicked(MusicProvider provider)
        {
            ProviderClicked?.Invoke(provider);
        }

    }
}
