// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using WebKit;

namespace UltraMusic.Views
{
	public partial class WebRendererController : NSViewController
	{
		public WebRendererController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

        }
    }
}
